let code1;
code1 = 7+3;
let code2 = (84-4)/2;
console.log(code2);
console.log(code1);
let code3 = 41%2+38;
console.log(code3);
let message ="The vault has been secured. The combination is:";
console.log(message);
let codeA = code1+"-"+code2+"-"+code3;
console.log(codeA);
let codeB = `${code1}-${code2}-${code3}`;
console.log(codeB);
console.log(message,codeA,codeB);